[package]
name = "html-outliner"
version = "0.1.2"
authors = ["Magic Len <len@magiclen.org>"]
edition = "2018"
repository = "https://github.com/magiclen/html-outliner"
homepage = "https://magiclen.org/rust-html-outliner"
keywords = ["html", "outline", "outliner"]
categories = ["parser-implementations"]
description = "Outline HTML documents for better SEO."
readme = "README.md"
license = "MIT"
include = ["src/**/*", "Cargo.toml", "README.md", "LICENSE"]

[badges.travis-ci]
repository = "magiclen/html-outliner"
branch = "master"

[dependencies]
kuchiki = "0.8.0"
regex = "1"
lazy_static = "1.4"